
CCREATE TABLE orders (
    order_id INT NOT NULL AUTO_INCREMENT,
    cart_id INT,
    order_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    order_desc VARCHAR(255),
    order_fee DECIMAL(7, 2),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (order_id)
);
