
CREATE TABLE categories (
    category_id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    parent_category_id INT(11),
    category_title VARCHAR(255),
    image_url VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
